emmet.songLoader = (function() {
    var startLoad = function(finalCallback) {
        $.ajax({
            url: "getsongs.php",
            dataType: "json",
            success: function(data, textStatus, jqXHR) {
                processSongData(data, finalCallback);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.error("Error when loading songs. HTTP status: '"+jqXHR.status+"', status text: '"+jqXHR.statusText+"', "+
                        "response text: '"+jqXHR.responseText+"', text status: '"+textStatus+"'.");
                emmet.notifier.showFatal("Énekbetöltési hiba",
                        "Az Emmet nem tudja betölteni az énekeket. A hiba részletei a fejlesztői konzolon találhatók."
                );
            },
        });
    };
    
    var processSongData = function(songData, finalCallback) {
        for (bookNo in songData) {
            var songBook = songData[bookNo];
            for (songNo in songBook.songs) {
                var song = songBook.songs[songNo];
                
                // Add displayed song number (remove autogenerated IDs)
                song.displayNumber = song.number.startsWith("ZZZZZ::EMMET-AUTO::") ? "" : song.number;
                
                for (var i = 0; i < song.verses.length; i++) {
                    var verse = song.verses[i];
                    verse.displayCode = getDisplayedVerseCode(verse.code);
                    verse.tokenizedLines = emmet.search.tokenizeVerseLines(verse.lines);
                }
            }
        }
        
        finalCallback(songData);
    };
    
    var getDisplayedVerseCode = function(verseCode) {
        var type = verseCode.substring(0, 1);
        var number = verseCode.substring(1);
        var dispCode = "";
        
        if (type == "C") {dispCode += "Refrén ";}
        else if (type == "B") {dispCode += "Átkötés ";}
        else if (type == "V") {dispCode += "Versszak ";}
        else if (type == "P") {dispCode += "Előrefrén ";}
        
        dispCode += number;
        
        return dispCode;
    };
    
    return {
        loadSongs: function(callback) {
            startLoad(callback);
        },
    };
})();