emmet.songLoader = (function() {
    var startLoad = function(finalCallback) {
        $.ajax({
            url: "getsongs.php",
            dataType: "json",
            success: function(data, textStatus, jqXHR) {
                try {
                    processSongData(data, finalCallback);
                } catch (e) {
                    console.error(e);
                    emmet.notifier.showSongLoadingError(e.hasOwnProperty("stack") ? e.stack : "(error not available)");
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
                var errorMsg = "Error when loading songs.\nHTTP status: '"+jqXHR.status+"'\nStatus text: '"+jqXHR.statusText+"'\n"+
                        "Text status: '"+textStatus+"'";
                console.error(errorMsg);
                console.error("Response text:'"+jqXHR.responseText+"'");
                emmet.notifier.showSongLoadingError(errorMsg);
            },
        });
    };
    
    var processSongData = function(songData, finalCallback) {
        for (bookNo in songData) {
            var songBook = songData[bookNo];
            for (songNo in songBook.songs) {
                var song = songBook.songs[songNo];
                
                // Add displayed song number (remove autogenerated IDs)
                song.displayNumber = song.number.startsWith("ZZZZZ::EMMET-AUTO::") ? "" : song.number;
                
                for (var i = 0; i < song.verses.length; i++) {
                    var verse = song.verses[i];
                    verse.displayCode = getDisplayedVerseCode(verse.code);
                    verse.isChorus = isChorus(verse.code);
                    verse.isBridge = isBridge(verse.code);
                    verse.tokenizedLines = emmet.search.tokenizeVerseLines(verse.lines);
                }
            }
        }
        
        finalCallback(songData);
    };
    
    var getDisplayedVerseCode = function(verseCode) {
        var type = verseCode.substring(0, 1);
        var number = verseCode.substring(1);
        var dispCode = "";
        
        if (type == "C") {dispCode += "R";}
        else if (type == "B") {dispCode += "Á";}
        else if (type == "P") {dispCode += "E";}
        
        dispCode += number;
        
        return dispCode;
    };

    var isChorus = function(verseCode) {
        return verseCode.substring(0, 1) == "C";
    };
    
    var isBridge = function(verseCode) {
        return verseCode.substring(0, 1) == "B";
    }
    
    return {
        loadSongs: function(callback) {
            startLoad(callback);
        },
        isChorus: isChorus,
        isBridge: isBridge,
    };
})();